version: '3'
services: 
    mysql1:
        image: mysql:5.7
        ports:
            - 13306:3306
        environment: 
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    mysql2:
        image: mysql:5.7
        ports:
            - 23306:3306
        environment: 
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    mysql-data:
        build: .
        VOLUME: /var/lib/mysql
        CMD: ["bin/true"]